modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0"

[[mods]]
modId="skyislands"
version="${version}"
displayName="Sky Islands"
description='''Adds skyblock world types to the world creation screen: Classic SkyBlock, Small SkyBlock and Single Block. Normal biome distribution, normal seeds. 在创建世界界面添加空岛世界类型：经典空岛、小型空岛、单块空岛。'''

[[dependencies.skyislands]]
modId="neoforge"
type="required"
versionRange="[21.9.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.skyislands]]
modId="minecraft"
type="required"
versionRange="[1.21.9,1.21.10)"
ordering="NONE"
side="BOTH"
