buildscript {
    repositories {
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.5.0'
group = 'dev.skyislands'
archivesBaseName = 'skyislands-forge-1.12.2'

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = '1.12.2-14.23.5.2847'
    runDir = 'run'
    // Final stable MCP mappings for the 1.12.2 line (de.oceanlabs.mcp:mcp_stable-39-1.12).
    mappings = 'stable_39'
    makeObfSourceJar = false
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.aliyun.com/repository/public' }
}

dependencies {
}

processResources {
    // this will ensure that the mcmod.info version is replaced
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
